/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendario: typeof import('./components/calendario.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    'Orçamentos': typeof import('./components/orçamentos.vue')['default']
    README: typeof import('./components/README.md')['default']
    Relatorios: typeof import('./components/relatorios.vue')['default']
    Resumos: typeof import('./components/resumos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TransactionList: typeof import('./components/TransactionList.vue')['default']
    Transactions: typeof import('./components/transactions.vue')['default']
  }
}
