/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    Calendario: typeof import('./components/Calendario.vue')['default']
    FinancialSummary: typeof import('./components/FinancialSummary.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    'Orçamentos': typeof import('./components/Orçamentos.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    PreviewModal: typeof import('./components/PreviewModal.vue')['default']
    README: typeof import('./components/README.md')['default']
    Relatorios: typeof import('./components/Relatorios.vue')['default']
    Resumos: typeof import('./components/Resumos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TransactionList: typeof import('./components/TransactionList.vue')['default']
    Transactions: typeof import('./components/Transactions.vue')['default']
  }
}
